version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "traffic-service"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-l7b0fsgwdd8r"
s3_prefix = "traffic-service"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
