AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  traffic-service

  Traffic Aggregator Service. Create a common service which return in a common
  way all traffic events in Spain.

Globals:
  Function:
    Timeout: 30

Resources:
  TrafficAggregatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: traffic_aggregator.app.lambda_handler
      Runtime: python3.8
      Events:
        TrafficAggregatorAPI:
          Type: Api
          Properties:
            Path: /traffic
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TrafficAggregatorAPI:
    Description: "API Gateway endpoint URL for Prod stage for Traffic Aggregator function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/traffic/"
  TrafficAggregatorFunction:
    Description: "Traffic Aggregator Lambda Function ARN"
    Value: !GetAtt TrafficAggregatorFunction.Arn
  TrafficAggregatorFunctionIamRole:
    Description: "Implicit IAM Role created for Traffic Aggregator function"
    Value: !GetAtt TrafficAggregatorFunction.Arn
